// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(grunt) {
    'use strict';
    var config, x, _i, _len, _ref;
    _ref = ['grunt-browserify', 'grunt-contrib-clean', 'grunt-iced-coffee', 'grunt-contrib-uglify'];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      x = _ref[_i];
      grunt.loadNpmTasks(x);
    }
    config = function() {
      this.pkg = grunt.file.readJSON('package.json');
      this.clean = {
        build: ['build/*'],
        dist: ['dist/*']
      };
      this.coffee = {
        options: {
          bare: true
        }
      };
      this.uglify = {
        options: {
          preserveComments: 'some'
        }
      };
      this.browserify = {};
      this.coffee.main = {
        options: {
          join: true,
          sourceMap: true,
          runtime: 'window'
        },
        files: [
          {
            expand: true,
            cwd: 'src/',
            src: '*.{iced,coffee}',
            dest: 'src/',
            ext: '.js'
          }, {
            'index.js': 'index.coffee'
          }
        ]
      };
      this.browserify.main = {
        options: {
          browserifyOptions: {
            standalone: 'yaya',
            transform: ['brfs', 'coffeeify']
          }
        },
        files: [
          {
            'dist/yaya.js': 'index.js'
          }
        ]
      };
      this.uglify.main = {
        files: [
          {
            'dist/yaya.min.js': 'dist/yaya.js'
          }
        ]
      };
      grunt.registerTask('main', ['browserify:main']);
      grunt.registerTask('default', ['main']);
      return this;
    };
    return grunt.initConfig(new config);
  };

}).call(this);

//# sourceMappingURL=gruntfile.js.map
